# Generated by Django 2.0.7 on 2018-09-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address_st', models.CharField(default='', max_length=50)),
                ('address_city', models.CharField(default='', max_length=50)),
                ('address_state', models.CharField(default='', max_length=20)),
                ('address_zip', models.CharField(default='', max_length=10)),
                ('mls', models.CharField(default='', max_length=25)),
                ('description', models.TextField(default='')),
                ('price', models.IntegerField(default=0)),
                ('arv', models.IntegerField(default=0)),
                ('closing_cost', models.IntegerField(default=0)),
                ('repair_cost', models.IntegerField(default=0)),
                ('down_payment', models.IntegerField(default=0)),
                ('loan_rate', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('loan_points', models.IntegerField(default=0)),
                ('loan_fees', models.IntegerField(default=0)),
                ('amt_years', models.IntegerField(default=0)),
                ('typical_cap', models.DecimalField(decimal_places=3, default=0.0, max_digits=5)),
                ('rent', models.IntegerField(default=0)),
                ('other_income', models.IntegerField(default=0)),
                ('electric', models.IntegerField(default=0)),
                ('water_sewer', models.IntegerField(default=0)),
                ('pmi', models.IntegerField(default=0)),
                ('garbage', models.IntegerField(default=0)),
                ('hoa', models.IntegerField(default=0)),
            ],
        ),
    ]
