# Generated by Django 2.0.7 on 2018-09-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='annual_ex_growth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='annual_income_growth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='annual_propvalue_growth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='cap_ex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='ex_other',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='insurance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='management',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='repairs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='sales_ex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='taxes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysis',
            name='vacancy',
            field=models.IntegerField(default=0),
        ),
    ]
