# Generated by Django 2.0.7 on 2018-09-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_auto_20180929_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='amt_years',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='annual_ex_growth',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='annual_income_growth',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='annual_propvalue_growth',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='cap_ex',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='down_payment',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='loan_rate',
            field=models.DecimalField(decimal_places=3, default=5.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='management',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='repairs',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='sales_ex',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='typical_cap',
            field=models.DecimalField(decimal_places=3, default=5.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='vacancy',
            field=models.IntegerField(default=5),
        ),
    ]
